name: Update Dataset Table

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight
  push:
    paths:
      - datasets/**
      - scripts/update_readme.py

jobs:
  update-table:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Run update script
        run: python scripts/update_readme.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-update dataset table" || echo "No changes to commit"
          git push
